package client

// SandboxPhase is the observed lifecycle phase from cellar-gateway.
type SandboxPhase string

const (
	PhasePending  SandboxPhase = "pending"
	PhaseStarting SandboxPhase = "starting"
	PhaseRunning  SandboxPhase = "running"
	PhaseStopped  SandboxPhase = "stopped"
	PhaseFailed   SandboxPhase = "failed"
)

// Mount is a host bind mount.
type Mount struct {
	Source   string `json:"source,omitempty"`
	Target   string `json:"target,omitempty"`
	ReadOnly bool   `json:"readOnly,omitempty"`
}

// Resources are container resource limits.
type Resources struct {
	CPUNanoCores int64 `json:"cpuNanoCores,omitempty"`
	MemoryBytes  int64 `json:"memoryBytes,omitempty"`
}

// NetworkRule matches destinations for egress policy.
type NetworkRule struct {
	Hosts     []string `json:"hosts,omitempty"`
	Ports     []uint32 `json:"ports,omitempty"`
	Protocols []string `json:"protocols,omitempty"`
}

// DNSPolicy filters name resolution.
type DNSPolicy struct {
	Mode  string   `json:"mode,omitempty"`
	Names []string `json:"names,omitempty"`
}

// NetworkPolicy is enforced by the userspace egress proxy.
type NetworkPolicy struct {
	Mode  string        `json:"mode,omitempty"`
	DNS   *DNSPolicy    `json:"dns,omitempty"`
	Rules []NetworkRule `json:"rules,omitempty"`
}

// SandboxSpec is the desired sandbox configuration.
type SandboxSpec struct {
	Image      string         `json:"image,omitempty"`
	Command    []string       `json:"command,omitempty"`
	Args       []string       `json:"args,omitempty"`
	Env        []string       `json:"env,omitempty"`
	WorkingDir string         `json:"workingDir,omitempty"`
	Mounts     []Mount        `json:"mounts,omitempty"`
	Resources  *Resources     `json:"resources,omitempty"`
	Network    *NetworkPolicy `json:"network,omitempty"`
	// Runtime is a language preset (node-26, bun-1.3, python-3.13, go-1.26).
	Runtime string `json:"runtime,omitempty"`
}

// SandboxStatus is observed runtime state.
type SandboxStatus struct {
	Phase              string `json:"phase,omitempty"`
	ContainerID        string `json:"containerId,omitempty"`
	ExitCode           int32  `json:"exitCode,omitempty"`
	Message            string `json:"message,omitempty"`
	StartedAtUnixNano  int64  `json:"startedAtUnixNano,omitempty"`
	FinishedAtUnixNano int64  `json:"finishedAtUnixNano,omitempty"`
	UpdatedAtUnixNano  int64  `json:"updatedAtUnixNano,omitempty"`
}

// SandboxSnapshot is the wire shape returned by the gateway (no behavior).
type SandboxSnapshot struct {
	ID                string         `json:"id,omitempty"`
	Spec              *SandboxSpec   `json:"spec,omitempty"`
	NodeID            string         `json:"nodeId,omitempty"`
	DesiredState      string         `json:"desiredState,omitempty"`
	Status            *SandboxStatus `json:"status,omitempty"`
	CreatedAtUnixNano int64          `json:"createdAtUnixNano,omitempty"`
	UpdatedAtUnixNano int64          `json:"updatedAtUnixNano,omitempty"`
}

// SandboxCreateRequest creates a sandbox.
type SandboxCreateRequest struct {
	Spec *SandboxSpec `json:"spec,omitempty"`
	// SandboxID is generated by the server when omitted.
	SandboxID string `json:"sandboxId,omitempty"`
}

type sandboxListResponse struct {
	Sandboxes []SandboxSnapshot `json:"sandboxes"`
}

type sandboxUpdateNetworkRequest struct {
	SandboxID string         `json:"sandboxId"`
	Network   *NetworkPolicy `json:"network,omitempty"`
}
