package client

import (
	"encoding/json"
	"fmt"
	"strconv"
)

// SandboxPhase is the observed lifecycle phase from cellar-gateway.
type SandboxPhase string

const (
	PhasePending  SandboxPhase = "pending"
	PhaseStarting SandboxPhase = "starting"
	PhaseRunning  SandboxPhase = "running"
	PhaseStopped  SandboxPhase = "stopped"
	PhaseFailed   SandboxPhase = "failed"
)

// FlexInt64 unmarshals JSON numbers or protobuf-JSON string-encoded int64s.
type FlexInt64 int64

func (v *FlexInt64) UnmarshalJSON(b []byte) error {
	if string(b) == "null" || len(b) == 0 {
		*v = 0
		return nil
	}
	if b[0] == '"' {
		var s string
		if err := json.Unmarshal(b, &s); err != nil {
			return err
		}
		if s == "" {
			*v = 0
			return nil
		}
		n, err := strconv.ParseInt(s, 10, 64)
		if err != nil {
			return fmt.Errorf("flex int64: %w", err)
		}
		*v = FlexInt64(n)
		return nil
	}
	var n int64
	if err := json.Unmarshal(b, &n); err != nil {
		return err
	}
	*v = FlexInt64(n)
	return nil
}

func (v FlexInt64) MarshalJSON() ([]byte, error) {
	return json.Marshal(int64(v))
}

func (v FlexInt64) Int64() int64 { return int64(v) }

// Mount is a host bind mount.
type Mount struct {
	Source   string `json:"source,omitempty"`
	Target   string `json:"target,omitempty"`
	ReadOnly bool   `json:"readOnly,omitempty"`
}

// Resources are container resource limits.
type Resources struct {
	CPUNanoCores FlexInt64 `json:"cpuNanoCores,omitempty"`
	MemoryBytes  FlexInt64 `json:"memoryBytes,omitempty"`
}

// NetworkRule matches destinations for egress policy.
type NetworkRule struct {
	Hosts     []string `json:"hosts,omitempty"`
	Ports     []uint32 `json:"ports,omitempty"`
	Protocols []string `json:"protocols,omitempty"`
}

// DNSPolicy filters name resolution.
type DNSPolicy struct {
	Mode  string   `json:"mode,omitempty"`
	Names []string `json:"names,omitempty"`
}

// NetworkPolicy is enforced by the userspace egress proxy.
type NetworkPolicy struct {
	Mode  string        `json:"mode,omitempty"`
	DNS   *DNSPolicy    `json:"dns,omitempty"`
	Rules []NetworkRule `json:"rules,omitempty"`
}

// SandboxSpec is the desired sandbox configuration.
type SandboxSpec struct {
	Image      string         `json:"image,omitempty"`
	Command    []string       `json:"command,omitempty"`
	Args       []string       `json:"args,omitempty"`
	Env        []string       `json:"env,omitempty"`
	WorkingDir string         `json:"workingDir,omitempty"`
	Mounts     []Mount        `json:"mounts,omitempty"`
	Resources  *Resources     `json:"resources,omitempty"`
	Network    *NetworkPolicy `json:"network,omitempty"`
	// Runtime is a language preset (node-26, bun-1.3, python-3.13, go-1.26).
	Runtime string `json:"runtime,omitempty"`
}

// SandboxStatus is observed runtime state.
type SandboxStatus struct {
	Phase              string    `json:"phase,omitempty"`
	ContainerID        string    `json:"containerId,omitempty"`
	ExitCode           int32     `json:"exitCode,omitempty"`
	Message            string    `json:"message,omitempty"`
	StartedAtUnixNano  FlexInt64 `json:"startedAtUnixNano,omitempty"`
	FinishedAtUnixNano FlexInt64 `json:"finishedAtUnixNano,omitempty"`
	UpdatedAtUnixNano  FlexInt64 `json:"updatedAtUnixNano,omitempty"`
}

// SandboxSnapshot is the wire shape returned by the gateway (no behavior).
type SandboxSnapshot struct {
	ID                string         `json:"id,omitempty"`
	Spec              *SandboxSpec   `json:"spec,omitempty"`
	NodeID            string         `json:"nodeId,omitempty"`
	DesiredState      string         `json:"desiredState,omitempty"`
	Status            *SandboxStatus `json:"status,omitempty"`
	CreatedAtUnixNano FlexInt64      `json:"createdAtUnixNano,omitempty"`
	UpdatedAtUnixNano FlexInt64      `json:"updatedAtUnixNano,omitempty"`
}

// SandboxCreateRequest creates a sandbox.
type SandboxCreateRequest struct {
	Spec *SandboxSpec `json:"spec,omitempty"`
	// SandboxID is generated by the server when omitted.
	SandboxID string `json:"sandboxId,omitempty"`
}

type sandboxListResponse struct {
	Sandboxes []SandboxSnapshot `json:"sandboxes"`
}

type sandboxUpdateNetworkRequest struct {
	SandboxID string         `json:"sandboxId"`
	Network   *NetworkPolicy `json:"network,omitempty"`
}
