export interface Mount {
  source: string
  target: string
  readOnly: boolean
}

export interface Resources {
  cpuNanoCores: number
  memoryBytes: number
}

export interface NetworkRule {
  hosts: string[]
  ports: number[]
  protocols: string[]
}

export interface DNSPolicy {
  /** none | allowlist | denylist */
  mode: string
  names: string[]
}

export interface NetworkPolicy {
  /** none | allowlist | denylist */
  mode: string
  dns: DNSPolicy | undefined
  rules: NetworkRule[]
}

export interface SandboxSpec {
  /** Custom image; mutually exclusive with runtime. */
  image: string
  command: string[]
  args: string[]
  env: string[]
  workingDir: string
  mounts: Mount[]
  resources: Resources | undefined
  network: NetworkPolicy | undefined
  /** Language preset (node-26, bun-1.3, python-3.13, go-1.26). */
  runtime: string
}

/** Observed lifecycle phase from cellar-gateway. */
export type SandboxPhase = 'pending' | 'starting' | 'running' | 'stopped' | 'failed'

export interface SandboxStatus {
  phase: SandboxPhase | string
  containerId: string
  exitCode: number
  message: string
  startedAtUnixNano: number
  finishedAtUnixNano: number
  updatedAtUnixNano: number
}

/** Wire/snapshot shape returned by the gateway (no behavior). */
export interface SandboxSnapshot {
  id: string
  spec: SandboxSpec | undefined
  nodeId: string
  desiredState: string
  status: SandboxStatus | undefined
  createdAtUnixNano: number
  updatedAtUnixNano: number
}

export interface SandboxCreateRequest {
  spec: SandboxSpec | undefined
  /** Generated by the server when omitted. */
  sandboxId: string
}

export interface SandboxUpdateNetworkRequest {
  sandboxId: string
  network: NetworkPolicy | undefined
}

export interface SandboxListResponse {
  sandboxes: SandboxSnapshot[]
}
